# cmake/build_system_bootstrap.cmake
#
# DO NOT EDIT THIS FILE. It is a standard bootstrap script for all KIS packages.
#
# This script is included by a package's top-level CMakeLists.txt ONLY when
# that package is being built as a standalone project. It is responsible for:
#   1. Fetching the KIS build system.
#   2. Including the core build engine.
#   3. Calling the standalone entrypoint to orchestrate the build.

message(STATUS "--- KIS Package Standalone Bootstrap ---")

# --- 1. Fetch the KIS Build System ---
# The build system provides all the `kis_*` functions needed to configure
# this package and its dependencies.
include(FetchContent)
FetchContent_Declare(
    kis_build_system
    # --- CONFIGURE THIS ---
    # Replace with the actual URL of your build system repository
    GIT_REPOSITORY https://github.com/Paolo-Oliverio/kis_build_system.git
    GIT_TAG        main # Or a specific version tag like v1.2.3
)
FetchContent_MakeAvailable(kis_build_system)

# --- 2. Include the Core Build Engine ---
# This makes all build system functions and public entrypoints available.
include(kis_build_system)

# --- 3. Execute the Standalone Build Process ---
# This single command orchestrates the entire dependency resolution
# (cloning first-party deps, fetching third-party deps) and then
# configures the entire project.
kis_bootstrap_standalone()